[package]
name = "blogger"
version = "1.0.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
serde = "1.0.219"
serde_json = "1.0.140"
thiserror = "2.0.12"
url = { version = "2.5.4", features = ["serde"] }
